=== marcust/jzuul/org/jzuul/engine/dtd/gamefile.dtd
<!ELEMENT gamefile (description?,map*,player?,history?,dialogs*,gameobjects?)>
		<!ATTLIST gamefile version CDATA "1.0">
	<!--<!ATTLIST gamefile xmlns:xi CDATA "http://www.w3.org/2003/XInclude"> -->	

	<!ELEMENT map (room+|transitionroom)*>
		<!ATTLIST map name CDATA #REQUIRED>
		<!ATTLIST map startroom CDATA #REQUIRED>

	<!ELEMENT room (description,image?,contents?, ways?,views?,event*)>
		<!ATTLIST room class CDATA #REQUIRED>
		<!ATTLIST room name CDATA #REQUIRED>
		
	<!ELEMENT image EMPTY>
		<!ATTLIST image file CDATA #REQUIRED>

	<!ELEMENT transitionroom (precondition*,ways*)>
		<!ATTLIST transitionroom name CDATA #REQUIRED>
		<!ATTLIST transitionroom final (true|false) "false">
		<!ATTLIST transitionroom target CDATA #REQUIRED>
		
	<!ELEMENT precondition EMPTY>
		<!ATTLIST precondition item CDATA #REQUIRED>

	<!ELEMENT description (#PCDATA)>
	
	<!ELEMENT contents (item|character)*>

	<!ELEMENT item EMPTY> 
		<!ATTLIST item name CDATA #REQUIRED>

	<!ELEMENT character EMPTY>
		<!ATTLIST character name CDATA #REQUIRED>
		<!ATTLIST character dialog CDATA "1">

	<!ELEMENT ways (way+)>

	<!ELEMENT way EMPTY>
		<!ATTLIST way direction (north|east|south|west|above|below) #REQUIRED>
		<!ATTLIST way room CDATA #REQUIRED>

	<!ELEMENT views (view+)>
	
	<!ELEMENT view (#PCDATA)>
		<!ATTLIST view direction (north|east|south|west|above|below)  #REQUIRED> 

	<!ELEMENT player (contents|target)*>
		<!ATTLIST player position CDATA #REQUIRED>
		<!ATTLIST player map CDATA #REQUIRED>
		<!ATTLIST player name CDATA "Player">
	
	<!ELEMENT target (description,condition,creator?)>
	
	<!ELEMENT condition EMPTY>
		<!ATTLIST condition type (give|talk) #REQUIRED>
		<!ATTLIST condition value CDATA #REQUIRED>
		
	<!ELEMENT creator EMPTY>
		<!ATTLIST creator name CDATA #REQUIRED>
		
	<!ELEMENT history (command*)>
	<!ELEMENT command (#PCDATA)>
	
	<!ELEMENT dialogs (dialog-owner+)>
		
	<!ELEMENT  dialog-owner (dialog+)>
		<!ATTLIST dialog-owner name CDATA #REQUIRED>
			
	<!ELEMENT dialog (phase|precondition)*>
				
	<!ELEMENT phase (object|reference)*>
	
	<!ELEMENT object (say,reply)>
		<!ATTLIST object id CDATA #REQUIRED>
		<!ATTLIST object type (dialog_continue|dialog_custom_result_1|dialog_custom_result_2|dialog_custom_result_3|dialog_error|dialog_npc_give|dialog_npc_take|dialog_end_failure|dialog_end_success) "dialog_end_failure">
		<!ATTLIST object nextphase CDATA "0">
	
	<!ELEMENT reference EMPTY>
		<!ATTLIST reference id CDATA #REQUIRED>
	
	<!ELEMENT say (#PCDATA)>
	<!ELEMENT reply (#PCDATA)>
		
	<!ELEMENT gameobjects (characters?,items?)>
	
	<!ELEMENT characters (person+)>
	
	<!ELEMENT person (description,action?,property*,event*)>
		<!ATTLIST person name CDATA #REQUIRED>

	<!ELEMENT action EMPTY>
		<!ATTLIST action type (moveRandom|leaveRoom|deleteItem) #IMPLIED>
		
	<!ELEMENT property EMPTY>
		<!ATTLIST property name (useable|takeable|size|deleteonuse) #REQUIRED>
		<!ATTLIST property value CDATA #REQUIRED>

	<!ELEMENT event (actions)> 
		<!ATTLIST event name (default|takeup|drop|playerenter|playerleave|use|dialog_continue|dialog_custom_result_1|dialog_custom_result_2|dialog_custom_result_3|dialog_error|dialog_npc_give|dialog_npc_take|dialog_end_failure|dialog_end_success|use_success|use_failure|timer) #REQUIRED>
		
	<!ELEMENT items (gameitem+)	>
	
	<!ELEMENT gameitem (description,property*,event*,combinations*)>
		<!ATTLIST gameitem name CDATA #REQUIRED>
		
	<!ELEMENT combinations (with-object*)>
	
	<!ELEMENT actions (target*,action*,player-say*,npc-say*,inventory-item*,room-item*,alter-item*,delete-item*,random-success?)>

	<!ELEMENT with-object (actions)>
		<!ATTLIST with-object name CDATA #REQUIRED>
		
	<!ELEMENT inventory-item (#PCDATA)>
	<!ELEMENT room-item (#PCDATA)>

	<!ELEMENT alter-item (#PCDATA)>
	<!ATTLIST alter-item property CDATA #REQUIRED>

	<!ELEMENT delete-item (#PCDATA)>
	<!ELEMENT random-success EMPTY>

	<!ELEMENT player-say (#PCDATA)>
	<!ELEMENT npc-say (#PCDATA)>

=== marcust/jzuul/org/jzuul/engine/test/resources/circle.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/org/jzuul/engine/dtd/gamefile.xsl" ?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">
<gamefile version="1.0">
<map name="default" startroom="test1">
<room class="org.jzuul.engine.rooms.Room" name="test1">
	<description>ein Testraum</description>
	<ways>
		<way direction="north" room="test2" />
	</ways>
</room>
<room class="org.jzuul.engine.rooms.Room" name="test2">
	<description>ein Testraum 2</description>
	<ways>
		<way direction="north" room="test1" />
	</ways>
</room>
</map>
</gamefile>

=== marcust/jzuul/org/jzuul/games/zuul/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/org/jzuul/engine/dtd/gamefile.xsl" ?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">
<gamefile version="1.0">
<history>
	<command>take Cat</command>
	<command>help</command>
	<command>help look</command>
	<command>look north</command>
	<command>look east</command>
	<command>look south</command>	
	<command>look west</command>	
	<command>look down</command>	
	<command>look up</command>	
	<command>help inspect</command>
	<command>inspect Cat</command>
	<command>look Tree</command>
	<command>help take</command>
	<command>take Knife</command>
	<command>help inspect</command>
	<command>inspect Apple</command>
	<command>help inv</command>
	<command>inv</command>
	<command>help use</command>
	<command>use Knife with Apple</command>
	<command>look</command>
	<command>take Apfelschalen</command>
	<command>use Knife with Cat</command>
	<command>use Knife</command>
	<command>use Knife with Tree</command>
	<command>inspect Tree</command>
	<command>inv</command>
	<command>use Geschaelterapfel</command>
	<command>inv</command>
	<command>use Apfelschalen</command>
	<command>inspect Hacker</command>
	<command>talk to Hacker</command>
	<command>1</command>
	<command>talk to Hacker</command>
	<command>3</command>
	<command>2</command>
	<command>help go</command>
	<command>go north</command>
	<command>go back</command>
	<command>go back</command>
	<command>go up</command>
	<command>take Mate</command>
	<command>inv</command>
	<command>go down</command>
	<command>inspect Mate</command>
	<command>inspect Apfelschalen</command>
	<command>inspect cat</command>
	<command>inspect knife</command>
	<command>go south</command>
	<command>give Mate to Hacker</command>
	<command>talk to Hacker</command>
	<command>1</command>
	<command>do nothing</command>
	<command>drink</command>
	<command>eat</command>	
	<command>help drop</command>
	<command>drop Apfelschalen</command>
	<command>drop Cat</command>
	<command>drop Knife</command>
	<command>hallo</command>
	<command>sleep</command>
</history>
</gamefile>

=== marcust/jzuul/org/jzuul/games/shoot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">

<gamefile version="1.0">
  <description>Welcome to shoot the Xerces developer</description>
  <map name="default" startroom="eingang">
    <room class="org.jzuul.engine.rooms.Room" name="eingang">
      <contents>
        <item name="gun" />
      </contents>
      <description>Eine düstere Welt</description>
      <ways />
      <views />
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="hölle">
      <description>ein sehr warmer Raum</description>
      <contents>
        <character name="xerces_developer" dialog="1" />
      </contents>
      <ways>
        <way direction="north" room="eingang" />
      </ways>
      <event name="timer">
        <actions>
          <npc-say>Hallo, ich bin ein neuer Xerces core developer</npc-say>
          <room-item>xerces_developer</room-item>
          <delete-item>leiche</delete-item>
        </actions>
      </event>
    </room>
  </map>
  <player position="haupteingang" map="default" name="Player" />
  <gameobjects>
    <characters>
      <person name="xerces_developer">
        <description>Ein Xerces Core Entwickler</description>
        <action type="moveRandom" />
      </person>
    </characters>
    <items>
      <gameitem name="gun">
        <description>Ein wunderschöne Pischtole</description>
        <property name="takeable" value="true" />
        <property name="size" value="2" />
        <property name="useable" value="no" />
        <combinations>
          <with-object name="xerces_developer">
            <actions>
              <room-item>leiche</room-item>
              <player-say>Getroffen!</player-say>
              <npc-say>Argh</npc-say>
              <delete-item>xerces_developer</delete-item>
            </actions>
          </with-object>
        </combinations>
      </gameitem>
      <gameitem name="leiche">
        <description>Ein toter Xerces Developer</description>
      </gameitem>
    </items>
  </gameobjects>
</gamefile>

=== marcust/jzuul/org/jzuul/games/kegeln/initial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">

<gamefile version="1.0">
  <description>Welcome to JBowling ;-)

Manual: you got an infinite number of bowling balls
Manual: use them with the bowling alley until you got 5 winning points</description>
  <map name="default" startroom="bowling_alley">
    <room class="org.jzuul.engine.rooms.Room" name="bowling_alley">
      <description> at a wondefull bowling alley</description>
      <ways />
      <views>
        <view direction="north">the exit</view>
        <view direction="east">the bowling alley</view>
        <view direction="south">a couple of people</view>
        <view direction="west">a displey</view>
      </views>
      <contents>
        <item name="bowling_alley" />
      </contents>
    </room>
    <transitionroom name="ende" final="true" target="default">
      <precondition item="point" />
      <precondition item="point" />
      <precondition item="point" />
      <precondition item="point" />
      <precondition item="point" />
      <ways>
        <way direction="south" room="bowling_alley" />
      </ways>
    </transitionroom>
  </map>
  <player position="bowling_alley" map="default" name="Player">
    <target>
      <description>Play Bowling</description>
      <condition type="give" value="bowling_alley" />
    </target>
    <contents>
      <item name="bowling_ball" />
      <item name="bowling_ball" />
      <item name="bowling_ball" />
      <item name="bowling_ball" />
      <item name="bowling_ball" />
    </contents>
  </player>
  <gameobjects>
    <items>
      <gameitem name="bowling_ball">
        <description>a nice round bowling ball</description>
        <combinations>
          <with-object name="bowling_alley">
            <actions>
              <player-say>The ball makes it's way</player-say>
              <random-success />
            </actions>
          </with-object>
        </combinations>
        <property name="useable" value="false" />
        <property name="takeable" value="false" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="1" />
      </gameitem>
      <gameitem name="bowling_alley">
        <description>a long bowling alley</description>
        <property name="size" value="10" />
        <property name="useable" value="false" />
        <event name="use_success">
          <actions>
            <player-say>Strike!</player-say>
            <inventory-item>point</inventory-item>
          </actions>
        </event>
        <event name="use_failure">
          <actions>
            <player-say>Miss!</player-say>
          </actions>
        </event>
      </gameitem>
      <gameitem name="point">
        <description>a winning Point</description>
        <property name="size" value="1" />
      </gameitem>
    </items>
  </gameobjects>
</gamefile>

=== marcust/jzuul/autosave.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">

<gamefile version="1.0 RC 1">
  <map name="default" startroom="eingang">
    <room class="org.jzuul.engine.rooms.Room" name="flur">
      <description>im Flur</description>
      <contents />
      <ways>
        <way direction="south" room="commzone" />
        <way direction="west" room="labor" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="foyer">
      <description>in der Eingangshalle</description>
      <contents />
      <ways>
        <way direction="north" room="sekreteriat" />
        <way direction="east" room="commzone" />
        <way direction="south" room="eingang" />
        <way direction="west" room="mensa" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="fachschaft">
      <description>in der Fachschaft Informatik</description>
      <contents />
      <ways>
        <way direction="below" room="commzone" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="eingang">
      <description>vor dem Eingang der FH</description>
      <contents />
      <ways>
        <way direction="north" room="foyer" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="commzone">
      <description>in der Kommunikationszone</description>
      <contents />
      <ways>
        <way direction="north" room="flur" />
        <way direction="east" room="ausgang" />
        <way direction="west" room="foyer" />
        <way direction="above" room="fachschaft" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="mensa">
      <description>in der Mensa</description>
      <contents />
      <ways>
        <way direction="east" room="foyer" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="ausgang">
      <description>vor  dem Ausgang</description>
      <contents />
      <ways>
        <way direction="west" room="commzone" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="sekreteriat">
      <description>vor dem Sekreteriat</description>
      <contents />
      <ways>
        <way direction="south" room="foyer" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="labor">
      <description>im BÃ¶hmer Labor</description>
      <contents />
      <ways>
        <way direction="east" room="flur" />
      </ways>
    </room>
  </map>
  <player position="eingang" map="default" name="Player">
    <contents>
      <item name="mate" />
    </contents>
  </player>
  <history />
</gamefile>

=== marcust/jzuul/org/jzuul/games/fh/initial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">

<gamefile version="1.0">
  <description />
  <map name="default" startroom="eingang">
    <room name="eingang" class="org.jzuul.engine.rooms.Room">
      <description>vor dem Eingang der FH</description>
      <image file="/org/jzuul/games/fh/eingang.jpg" />
      <ways>
        <way direction="north" room="foyer" />
      </ways>
      <views />
    </room>
    <room name="foyer" class="org.jzuul.engine.rooms.Room">
      <description>in der Eingangshalle</description>
      <image file="/org/jzuul/games/fh/foyer.jpg" />
      <ways>
        <way direction="north" room="sekreteriat" />
        <way direction="east" room="commzone" />
        <way direction="west" room="mensa" />
      </ways>
      <views />
    </room>
    <room name="mensa" class="org.jzuul.engine.rooms.Room">
      <description>in der Mensa</description>
      <image file="/org/jzuul/games/fh/mensa.jpg" />
      <ways />
      <views />
    </room>
    <room name="sekreteriat" class="org.jzuul.engine.rooms.Room">
      <description>vor dem Sekreteriat</description>
      <image file="/org/jzuul/games/fh/sekreteriat.jpg" />
      <ways />
      <views />
    </room>
    <room name="commzone" class="org.jzuul.engine.rooms.Room">
      <description>in der Kommunikationszone</description>
      <image file="/org/jzuul/games/fh/comzone.jpg" />
      <ways>
        <way direction="north" room="flur" />
        <way direction="east" room="ausgang" />
        <way direction="above" room="fachschaft" />
      </ways>
      <views />
    </room>
    <room name="fachschaft" class="org.jzuul.engine.rooms.Room">
      <description>in der Fachschaft Informatik</description>
      <image file="/org/jzuul/games/fh/fachschaft.jpg" />
      <ways />
      <views />
    </room>
    <room name="ausgang" class="org.jzuul.engine.rooms.Room">
      <description>vor  dem Ausgang</description>
      <image file="/org/jzuul/games/fh/garten.jpg" />
      <ways />
      <views />
    </room>
    <room name="flur" class="org.jzuul.engine.rooms.Room">
      <description>im Flur</description>
      <image file="/org/jzuul/games/fh/flur.jpg" />
      <ways>
        <way direction="west" room="labor" />
      </ways>
      <views />
    </room>
    <room name="labor" class="org.jzuul.engine.rooms.Room">
      <description>im BÃ¶hmer Labor</description>
      <image file="/org/jzuul/games/fh/labor.jpg" />
      <ways />
      <views />
    </room>
  </map>
  <player name="Player" />
  <dialogs />
  <gameobjects>
    <characters />
    <items>
      <gameitem name="gral">
        <description>Der heilige Gral</description>
        <property name="useable" value="false" />
        <property name="takeable" value="true" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="2" />
      </gameitem>
    </items>
  </gameobjects>
</gamefile>

=== marcust/jzuul/org/jzuul/engine/test/resources/wellformed.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/org/jzuul/engine/dtd/gamefile.xsl" ?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">
<gamefile version="1.0" >
	<map name="default" startroom="haupteingang">
<room class="org.jzuul.engine.rooms.Room" name="hoersal">
	<description>in einem Vorlesungssaal</description>
	<ways>
		<way direction="west" room="haupteingang" />
	</ways>
</room>
<room class="org.jzuul.engine.rooms.Room" name="fachschaft">
	<description>in der Fachschaft Informatik</description>
	<contents>
		<item name="mate" />
		<item name="mate" />
		<item name="mate" />
	</contents>
	<ways>
		<way direction="east" room="beamer" />
		<way direction="below" room="commzone" />
	</ways>
	<event name="playerenter">
		<actions>
			<say>Hier riechts komisch!</say>
		</actions>
	</event>
</room>
<room class="org.jzuul.engine.rooms.Room" name="cafeteria">
	<description>in der Cafeteria der Uni</description>
	<ways>
		<way direction="east" room="haupteingang" />
	</ways>
</room>
<room class="org.jzuul.engine.rooms.Room" name="haupteingang">
	<description>vor dem Haupteingang der Universität</description>
	<contents>
		<item name="apple" />
		<character name="cat" dialog="1" />
		<character name="hacker" dialog="1" />
		<item name="knife" />
		<item name="tree" />
	</contents>
	<ways>
		<way direction="north" room="commzone" />
		<way direction="east" room="hoersal" />
		<way direction="south" room="labor" />
		<way direction="west" room="cafeteria" />
	</ways>
	<views>
		<view direction="north">einen steinigen weg</view>
		<view direction="east">eine große Tür</view>
		<view direction="south">eine kleine Tür</view>
		<view direction="west">eine Anzeigetafel</view>
	</views>
	<event name="timer">
		<actions>
			<say>Ein Apfel fällt vom Baum</say>		
			<room-item>apple</room-item>
		</actions>
	</event>

</room>
<room class="org.jzuul.engine.rooms.BeamRoom" name="beamer">
	<description>in einem Raum mit komischen Geräten</description>
	<ways>
		<way direction="west" room="fachschaft" />
	</ways>
</room>
<room class="org.jzuul.engine.rooms.Room" name="commzone">
	<description>in der Kommunikationszone</description>
	<contents>
		<character name="geist" />
		<character name="parrot" />
	</contents>
	<ways>
		<way direction="south" room="haupteingang" />
		<way direction="above" room="fachschaft" />
	</ways>
</room>
<room class="org.jzuul.engine.rooms.Room" name="labor">
	<description>in einem Rechnerraum</description>
	<ways>
		<way direction="north" room="haupteingang" />
		<way direction="east" room="buero" />
	</ways>
</room>
<room class="org.jzuul.engine.rooms.Room" name="buero">
	<description>im Verwaltungsbüro der Informatik</description>
	<ways>
		<way direction="west" room="labor" />
	</ways>
</room>
<transitionroom name="uebergang1" final="false" target="newmap">
	<precondition item="knife"/>
	<ways>
		<way direction="south" room="fachschaft" />
	</ways>
</transitionroom>
</map>
<map name="newmap" startroom="besenkammer">
	<room class="org.jzuul.engine.rooms.Room" name="besenkammer">
		<description>in einer Besenkammer</description>
		<ways>
			<way direction="north" room="abstellkammer" />
		</ways>
	</room>
	<room class="org.jzuul.engine.rooms.Room" name="abstellkammer">
		<description>in einer Abstellkammer</description>
		<ways>
			<way direction="south" room="besenkammer" />
		</ways>
	</room>
<transitionroom name="uebergang2" final="true" target="default">
	<precondition item="knife"/>
	<ways>
		<way direction="east" room="besenkammer" />
	</ways>
</transitionroom>
</map>
<player position="haupteingang" map="default">
	<target>
		<description>Such eine Person die dir weiterhilft</description>
		<condition type="talk" value="hacker" />
	</target>
</player>
<history>
</history>
<dialogs>
	<dialog-owner name="hacker">
		<dialog>
			<phase>
			<object id="1"  type="dialog_end_failure">
				<say>Hallo wie gehts</say>
				<reply>Könnte nicht schlechter sein</reply>
			</object>
			<object id="2" type="dialog_end_failure">
				<say>Was machst du da?</say>
				<reply>Was geht dich das an?!?</reply>
			</object>
			<object id="3" type="dialog_continue" nextphase="2">
				<say>Kannst du mir sagen was ich tun soll?</say>
				<reply>Vielleicht...</reply>
			</object>
		<object id="4" type="dialog_end_failure">
				<say>Wie war das nochmal mit Linux?</say>
				<reply>Willst du mich verarschen?</reply>
		</object>
		<object id="5" type="dialog_end_failure">
				<say>Möchtest du diese schöne Lederjacke kaufen?</say>
				<reply>Willst du mich verarschen?</reply>
		</object>
		</phase>
		<phase>
			<object id="6" type="dialog_end_failure">
				<say>Ich hab da dieses Windowsproblem...</say>
				<reply>Win... was? Kenne ich nicht</reply>
			</object>
			<reference id="2" />
			<reference id="4" />
			<object id="7" type="dialog_custom_result_1">

				<say>Was muss ich tun damit du mir bei diesem Problem hillfst?</say>
				<reply>Besorg mir Mate!</reply>
			</object>
		</phase>
		</dialog>
		<dialog>
			<precondition item="mate" />
			<phase>
				<object id="1" type="dialog_end_success">
					<say>Kannst du mir jetzt sagen was ich tun soll?</say>
					<reply>Imlementiere das Gameplay</reply>
				</object>
			</phase>
		</dialog>
	</dialog-owner>
</dialogs>
<gameobjects>
	<characters>
		<person name="hacker">
			<description>ein komischer Geek</description>
			<property name="useable" value="false" />
			<property name="takeable" value="false" />
			<property name="size" value="5" />		
			<event name="dialog_custom_result_1">
				<actions>
				<target>
					<description>Besorg dem Hacker Mate</description>
					<condition type="give" value="mate" />
				</target>
				</actions>
			</event>
		</person>		
		<person name="cat">
			<description>eine schwarze Katze</description>
			<property name="useable" value="false" />
			<property name="takeable" value="true" />
			<property name="size" value="1" />
			<event name="takeup">
				<actions>
				<say>Miauu!</say>
				</actions>
			</event>
			<event name="drop">
				<actions>
				<say>Mowww</say>
				</actions>
			</event>
			<event name="default">
				<actions>
				<action type="moveRandom" />
				</actions>
			</event>
		</person>
		
			<person name="parrot">
			<description>ein Papagei</description>
			<event name="playerleave">
				<actions>
				<say>Tschüss, Lora</say>
				</actions>
			</event>
			<event name="playerenter">
				<actions>
				<say>Hallo, Lora</say>
				</actions>
			</event>
		</person>
		
		<person name="geist">
			<description>ein guter Geist</description>
			<event name="playerenter">
				<actions>
				<action type="leaveRoom" />
				</actions>
			</event>
			
		</person>
		
	</characters>
	<items>
		
		<gameitem name="apfelschalen">
			<description>normale Apfelschalen</description>
			<property name="size" value="1" />
			<property name="useable" value="false" />
		</gameitem>
		
		<gameitem name="apple">
			<description>eine Apfel</description>
			<property name="size" value="2" />
			<property name="useable" value="false" />
		</gameitem>

		<gameitem name="geschaelterapfel">
			<description>eine geschaelter Apfel</description>
			<property name="size" value="2" />
			<property name="useable" value="true" />
			<property name="deleteonuse" value="true" />
			<event name="use">
				<actions>
				<say>Mmm, lecker</say>
				</actions>
			</event>
		</gameitem>
		
		<gameitem name="knife">
			<description>ein Kückenmesser</description>
			<property name="size" value="2" />
			<property name="useable" value="true" />
			<event name="use">
				<actions>
				<say>Autsch</say>
				</actions>
			</event>
			<combinations>

				<with-object name="apple">
					<actions>
					<say>Du hast den Apfel geschält, die Schalen fallen auf den Boden</say>
					<inventory-item>geschaelterapfel</inventory-item>
					<room-item>apfelschalen</room-item>
					<delete-item>apple</delete-item>
					</actions>
				</with-object>

				<with-object name="cat">
					<actions>
						<say>Ich will die Katze nicht verletzen</say>					
					</actions>
				</with-object>

				<with-object name="tree">
					<actions>
					<say>Du ritzt ein herz in den Baum</say>
					<alter-item property="description">Ein Baum mit einem Herz darin</alter-item>
					</actions>
				</with-object>

			</combinations>
		</gameitem>

		<gameitem name="tree">
			<description>Ein schöner Apfelbaum</description>
			<property name="takeable" value="false" />
			<property name="size" value="10" />
			<property name="useable" value="false" />
		</gameitem>
		
		<gameitem name="mate">
			<description>Wunderbar erfrischende Mate</description>
			<property name="takeable" value="true" />
			<property name="size" value="2" />
			<property name="useable" value="true" />
			<property name="deleteonuse" value="true" />
			<event name="use">
				<actions>
				<say>Sehr erfrischend</say>
				</actions>
			</event>
		</gameitem>
		
		
		
	</items>
</gameobjects>

</gamefile>
