=== marcust/jzuul/org/jzuul/games/zuul/gamefile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.jzuul.org" xmlns="http://www.jzuul.org" version="1.0">
    <xs:simpleType name="directions">
        <xs:restriction base="xs:token">
            <xs:enumeration value="north"/>
            <xs:enumeration value="east"/>
            <xs:enumeration value="south"/>
            <xs:enumeration value="west"/>
            <xs:enumeration value="above"/>
            <xs:enumeration value="below"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="dialog_events">
        <xs:restriction base="xs:token">
            <xs:enumeration value="dialog_continue"/>
            <xs:enumeration value="dialog_custom_result_1"/>
            <xs:enumeration value="dialog_custom_result_2"/>
            <xs:enumeration value="dialog_custom_result_3"/>
            <xs:enumeration value="dialog_error"/>
            <xs:enumeration value="dialog_npc_give"/>
            <xs:enumeration value="dialog_npc_take"/>
            <xs:enumeration value="dialog_end_failure"/>
            <xs:enumeration value="dialog_end_success"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="standard_events">
        <xs:restriction base="xs:token">
            <xs:enumeration value="default"/>
            <xs:enumeration value="takeup"/>
            <xs:enumeration value="drop"/>
            <xs:enumeration value="playerenter"/>
            <xs:enumeration value="playerleave"/>
            <xs:enumeration value="use"/>
            <xs:enumeration value="use_success"/>
            <xs:enumeration value="use_failure"/>
            <xs:enumeration value="timer"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="all_events">
        <xs:union memberTypes="standard_events dialog_events"/>
    </xs:simpleType>
    <xs:simpleType name="action_types">
        <xs:restriction base="xs:token">
            <xs:enumeration value="moveRandom"/>
            <xs:enumeration value="leaveRoom"/>
            <xs:enumeration value="deleteItem"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="gamefile">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="description"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="map"/>
                <xs:element minOccurs="0" ref="player"/>
                <xs:element minOccurs="0" ref="history"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="dialogs"/>
                <xs:element minOccurs="0" ref="gameobjects"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.gamefile"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.gamefile">
        <xs:attribute name="version" default="1.0"/>
    </xs:attributeGroup>
    <xs:element name="map">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element maxOccurs="unbounded" ref="room"/>
                <xs:element ref="transitionroom"/>
            </xs:choice>
            <xs:attributeGroup ref="attlist.map"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.map">
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attribute name="startroom" use="required" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="room">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element minOccurs="0" ref="image"/>
                <xs:element minOccurs="0" ref="contents"/>
                <xs:element minOccurs="0" ref="ways"/>
                <xs:element minOccurs="0" ref="views"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.room"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.room">
        <xs:attribute name="class" use="required" type="xs:string"/>
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="image">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.image"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.image">
        <xs:attribute name="file" use="required" type="xs:anyURI"/>
    </xs:attributeGroup>
    <xs:element name="transitionroom">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="precondition"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="ways"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.transitionroom"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.transitionroom">
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attribute name="final" default="false" type="xs:boolean"/>
        <xs:attribute name="target" use="required"/>
    </xs:attributeGroup>
    <xs:element name="precondition">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.precondition"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.precondition">
        <xs:attribute name="item" use="required" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="contents">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="item"/>
                <xs:element ref="character"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="item">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.item"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.item">
        <xs:attribute name="name" use="required"/>
    </xs:attributeGroup>
    <xs:element name="character">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.character"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.character">
        <xs:attribute name="name" use="required" type="xs:string"/>
        <xs:attribute name="dialog" default="1" type="xs:positiveInteger"/>
    </xs:attributeGroup>
    <xs:element name="ways">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="way"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="way">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.way"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.way">
        <xs:attribute name="direction" use="required" type="directions"/>
        <xs:attribute name="room" use="required" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="views">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="view"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="view">
        <xs:complexType mixed="true">
            <xs:attributeGroup ref="attlist.view"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.view">
        <xs:attribute name="direction" use="required" type="directions"/>
    </xs:attributeGroup>
    <xs:element name="player">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="contents"/>
                <xs:element ref="target"/>
            </xs:choice>
            <xs:attributeGroup ref="attlist.player"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.player">
        <xs:attribute name="position" use="required" type="xs:string"/>
        <xs:attribute name="map" use="required" type="xs:string"/>
        <xs:attribute name="name" default="Player" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="target">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element ref="condition"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="condition">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.condition"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.condition">
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="give"/>
                    <xs:enumeration value="talk"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="value" use="required"/>
    </xs:attributeGroup>
    <xs:element name="history">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="command"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="command" type="xs:string"/>
    <xs:element name="dialogs">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="dialog-owner"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="dialog-owner">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="dialog"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.dialog-owner"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.dialog-owner">
        <xs:attribute name="name" use="required"/>
    </xs:attributeGroup>
    <xs:element name="dialog">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="phase"/>
                <xs:element ref="precondition"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="phase">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="object"/>
                <xs:element ref="reference"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="object">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="say"/>
                <xs:element ref="reply"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.object"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.object">
        <xs:attribute name="id" use="required" type="xs:nonNegativeInteger"/>
        <xs:attribute name="type" default="dialog_end_failure" type="dialog_events"/>
        <xs:attribute name="nextphase" default="0" type="xs:nonNegativeInteger"/>
    </xs:attributeGroup>
    <xs:element name="reference">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.reference"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.reference">
        <xs:attribute name="id" use="required"/>
    </xs:attributeGroup>
    <xs:element name="say" type="xs:string"/>
    <xs:element name="reply" type="xs:string"/>
    <xs:element name="gameobjects">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" ref="characters"/>
                <xs:element minOccurs="0" ref="items"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="characters">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="person"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element minOccurs="0" ref="action"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.person"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="player-say" type="xs:string"/>
    <xs:element name="npc-say" type="xs:string"/>
    <xs:attributeGroup name="attlist.person">
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="action">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.action"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.action">
        <xs:attribute name="type" type="action_types"/>
    </xs:attributeGroup>
    <xs:element name="property">
        <xs:complexType>
            <xs:attributeGroup ref="attlist.property"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.property">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="useable"/>
                    <xs:enumeration value="takeable"/>
                    <xs:enumeration value="size"/>
                    <xs:enumeration value="deleteonuse"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="value" use="required"/>
    </xs:attributeGroup>
    <xs:element name="event">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="actions">
                    <xs:attributeGroup ref="attlist.event"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.event">
        <xs:attribute name="name" use="required" type="all_events"/>
    </xs:attributeGroup>
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="gameitem"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="gameitem">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="property"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="event"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="combinations"/>
            </xs:sequence>
            <xs:attributeGroup ref="attlist.gameitem"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.gameitem">
        <xs:attribute name="name" use="required"/>
    </xs:attributeGroup>
    <xs:element name="combinations">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="with-object"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="actions">
        <xs:sequence>
            <xs:element ref="actions"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="actions">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="target"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="action"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="player-say"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="npc-say"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="inventory-item"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="room-item"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="alter-item"/>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="delete-item"/>
                <xs:element minOccurs="0" ref="random-success"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="with-object">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="actions">
                    <xs:attributeGroup ref="attlist.with-object"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.with-object">
        <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:attributeGroup>
    <xs:element name="inventory-item" type="xs:string"/>
    <xs:element name="room-item" type="xs:string"/>
    <xs:element name="alter-item">
        <xs:complexType mixed="true">
            <xs:attributeGroup ref="attlist.alter-item"/>
        </xs:complexType>
    </xs:element>
    <xs:attributeGroup name="attlist.alter-item">
        <xs:attribute name="property" use="required"/>
    </xs:attributeGroup>
    <xs:element name="delete-item" type="xs:string"/>
    <xs:element name="random-success">
        <xs:complexType/>
    </xs:element>
</xs:schema>

=== marcust/jzuul/org/jzuul/games/zuul/initial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gamefile SYSTEM "file:org/jzuul/engine/dtd/gamefile.dtd">

<gamefile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/zuul/org/jzuul/engine/dtd/gamefile.xsd" version="1.0">
  <description>Welcome to Zuul! Zuul is a new exciting game. 
   Enter 'help' when you need help.</description>
  <map name="default" startroom="mainentrance">
    <room class="org.jzuul.engine.rooms.Room" name="class">
      <description>in a classroom</description>
      <ways>
        <way direction="west" room="mainentrance" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="studentsroom">
      <description>in the student room for computer science students</description>
      <image file="/org/jzuul/games/zuul/bild3.jpg" />
      <contents>
        <item name="mate" />
        <item name="mate" />
        <item name="mate" />
      </contents>
      <ways>
        <way direction="east" room="beamer" />
        <way direction="below" room="commzone" />
      </ways>
      <event name="playerenter">
        <actions>
          <player-say>This room is creepy!</player-say>
        </actions>
      </event>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="cafeteria">
      <description>in the cafeteria</description>
      <ways>
        <way direction="east" room="mainentrance" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="mainentrance">
      <description>in front of the main entrance of the university</description>
      <image file="/org/jzuul/games/zuul/bild1.jpg" />
      <contents>
        <item name="apple" />
        <character name="cat" dialog="1" />
        <character name="hacker" dialog="1" />
        <item name="knife" />
        <item name="tree" />
      </contents>
      <ways>
        <way direction="north" room="commzone" />
        <way direction="east" room="class" />
        <way direction="south" room="labor" />
        <way direction="west" room="cafeteria" />
      </ways>
      <views>
        <view direction="north">a hard way</view>
        <view direction="east">a big door</view>
        <view direction="south">a small dor</view>
        <view direction="west">a display</view>
      </views>
      <event name="timer">
        <actions>
          <player-say>An apple falls of the tree</player-say>
          <room-item>apple</room-item>
        </actions>
      </event>
    </room>
    <room class="org.jzuul.engine.rooms.BeamRoom" name="beamer">
      <description>in a room full of strange stuff</description>
      <ways>
        <way direction="west" room="studentsroom" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="commzone">
      <description>in the students communication zone</description>
      <image file="/org/jzuul/games/zuul/bild2.jpg" />
      <ways>
        <way direction="south" room="mainentrance" />
        <way direction="above" room="studentsroom" />
      </ways>
      <contents>
        <character name="ghost" />
        <character name="parrot" />
      </contents>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="labor">
      <description>in a computer room</description>
      <ways>
        <way direction="north" room="mainentrance" />
        <way direction="east" room="buero" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="buero">
      <description>in the adminstrative buro</description>
      <ways>
        <way direction="west" room="labor" />
      </ways>
    </room>
    <transitionroom name="uebergang1" final="false" target="newmap">
      <precondition item="knife" />
      <ways>
        <way direction="south" room="studentsroom" />
      </ways>
    </transitionroom>
  </map>
  <map name="newmap" startroom="besenkammer">
    <room class="org.jzuul.engine.rooms.Room" name="besenkammer">
      <description>in a maintainance room</description>
      <ways>
        <way direction="north" room="abstellkammer" />
      </ways>
    </room>
    <room class="org.jzuul.engine.rooms.Room" name="abstellkammer">
      <description>in a store room</description>
      <ways>
        <way direction="south" room="besenkammer" />
      </ways>
    </room>
    <transitionroom name="uebergang2" final="true" target="default">
      <precondition item="knife" />
      <ways>
        <way direction="east" room="besenkammer" />
      </ways>
    </transitionroom>
  </map>
  <player position="mainentrance" map="default" name="Player">
    <target>
      <description>Find a person to help you</description>
      <condition type="talk" value="hacker" />
    </target>
  </player>
  <history />
  <dialogs>
    <dialog-owner name="hacker">
      <dialog>
        <phase>
          <object id="1" type="dialog_end_failure" nextphase="0">
            <say>Hi, how are you?</say>
            <reply>Couldn't be any worse</reply>
          </object>
          <object id="2" type="dialog_end_failure" nextphase="0">
            <say>What are you doing?</say>
            <reply>Mind your own business?!?</reply>
          </object>
          <object id="3" type="dialog_continue" nextphase="2">
            <say>Can you tell me what to do?</say>
            <reply>Maybe...</reply>
          </object>
          <object id="4" type="dialog_end_failure" nextphase="0">
            <say>What about Linux?</say>
            <reply>You're gonna make fun of me?</reply>
          </object>
          <object id="5" type="dialog_end_failure" nextphase="0">
            <say>Do you wanna buy this nice leather jacket?</say>
            <reply>Are you gonna make fun if me?</reply>
          </object>
        </phase>
        <phase>
          <object id="6" type="dialog_end_failure" nextphase="0">
            <say>I got this Windows problem...</say>
            <reply>Win... what? Don't know any about that</reply>
          </object>
          <reference id="2" />
          <reference id="4" />
          <object id="7" type="dialog_custom_result_1" nextphase="0">
            <say>What do I have to do to make you help me?</say>
            <reply>Get me some Mate!</reply>
          </object>
        </phase>
      </dialog>
      <dialog>
        <precondition item="mate" />
        <phase>
          <object id="1" type="dialog_end_success" nextphase="0">
            <say>Can you tell me what to do, now?</say>
            <reply>Create some games!</reply>
          </object>
        </phase>
      </dialog>
    </dialog-owner>
  </dialogs>
  <gameobjects>
    <characters>
      <person name="hacker">
        <description>a strange Geek</description>
        <event name="dialog_custom_result_1">
          <actions>
            <target>
              <description>Get the Hacker some Mate</description>
              <condition type="give" value="mate" />
            </target>
          </actions>
        </event>
        <property name="useable" value="false" />
        <property name="takeable" value="false" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="5" />
      </person>
      <person name="cat">
        <description>a black cat</description>
        <event name="takeup">
          <actions>
            <npc-say>Miauu!</npc-say>
          </actions>
        </event>
        <event name="drop">
          <actions>
            <npc-say>Mowww</npc-say>
          </actions>
        </event>
        <event name="default">
          <actions>
            <action type="moveRandom" />
          </actions>
        </event>
        <property name="useable" value="false" />
        <property name="takeable" value="true" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="1" />
      </person>
      <person name="parrot">
        <description>a parrot</description>
        <event name="playerleave">
          <actions>
            <npc-say>Bye, Lora</npc-say>
          </actions>
        </event>
        <event name="playerenter">
          <actions>
            <npc-say>Hello, Lora</npc-say>
          </actions>
        </event>
        <event name="timer">
          <actions>
            <npc-say>croak</npc-say>
          </actions>
        </event>
        <property name="useable" value="false" />
        <property name="takeable" value="false" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="0" />
      </person>
      <person name="ghost">
        <description>a good ghost</description>
        <event name="playerenter">
          <actions>
            <action type="leaveRoom" />
          </actions>
        </event>
        <property name="useable" value="false" />
        <property name="takeable" value="false" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="0" />
      </person>
    </characters>
    <items>
      <gameitem name="apple_skin">
        <description>usual apple skins</description>
        <property name="useable" value="false" />
        <property name="takeable" value="true" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="1" />
      </gameitem>
      <gameitem name="apple">
        <description>a red apple</description>
        <property name="useable" value="false" />
        <property name="takeable" value="true" />
        <property name="deleteonuse" value="false" />
        <property name="size" value="2" />
      </gameitem>
      <gameitem name="peeled_apple">
        <description>a peeled apple</description>
        <event name="use">
          <actions>
